### ISSUE TITLE
Add tag to classified transactions

### ISSUE THREAD

**Issue by Se7enair** [akopulko/ffiiitc#18]
First, WOW!
Installation, training and first correct guessed categorie in under 10min. 

Want to give some input for possible enhancements.
How about a tag beeing added to classified transactions, so that I know the category is added trough this. Or maybe a entry in the audit log?

And a little question: How often is the model trained?

**Comment by akopulko** [comment]
Thanks, I added this to potential enhancements. 
As for training, working on self tgraining vbased on transation updates, also you can [force](https://github.com/akopulko/ffiiitc#forced-training-of-your-model) training manually.

**Comment by Insomniacnomis** [comment]
Created pull request #21 to add this feature

**Comment by akopulko** [comment]
now merged #21

**Comment by dudu7731** [comment]
since this enhancements, data importer tags are removed, can you fix this ?
