### ISSUE TITLE
Create handler and endpoint to force training

### ISSUE THREAD

**Issue by akopulko** [akopulko/ffiiitc#6]
Roght now all training data is saved in .gob file on the attached volume. If you need to re-train the model, you need to delete file and then restart container. Would be good to have /force endpoint to trigger re-training of the model in case file get corrupted.

**Comment by Jack-XHP** [comment]
Yes that would be ideal, currently, I modify your code to retrain the classifier if the saved .gob mtime is older than certain days. The day can be passed in as a docker env variable. And it still works with `/learn` updated .gob will delay the training accordingly.
